image:
  registry: ccr.ccs.tencentyun.com
  repository: k3s-platform/platform-server
  tag: dev
  pullPolicy: Always
  pullSecrets:
    - tcr-platform-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

api:
  replicaCount: 1
  command: []
  args: 
    - api
  nodeSelector:
    platform-role: light
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

worker:
  replicaCount: 1
  command: []
  args: 
    - worker
  nodeSelector:
    platform-role: light
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

config:
  catalogPath: /app/configs/service-catalog.yaml
  serviceCatalog: |
    version: v1

    services:
      - name: forum-api
        displayName: Forum API
        owner: worryyy

        environments:
          - name: dev
            namespace: app

            branchPolicy:
              defaultBranch: main
              allowedBranches:
                - main
                - develop
                - feature/*

            git:
              repo: https://github.com/worryyy/forum-app.git
              chartPath: k3s/charts/forum-api
              valuesFile: k3s/helm-values/workloads/forum-api-business.yaml

            image:
              repository: ccr.ccs.tencentyun.com/k3s-platform/server
              tagPolicy: git-sha
              requireDigest: false

            jenkins:
              mode: legacy
              jobName: forum-api-pipeline

            argocd:
              application: forum-api
              namespace: argocd

            kubernetes:
              namespace: app
              deployment: forum-api
              service: forum-api
              container: forum-api

            health:
              healthPath: /healthz
              readyPath: /readyz

env:
  POSTGRES_HOST: platform-postgresql.platform.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: platform_db
  POSTGRES_USER: platform_user

  RABBITMQ_HOST: platform-rabbitmq.platform.svc.cluster.local
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: platform_user

  JENKINS_BASE_URL: http://jenkins.cicd.svc.cluster.local:8080
  JENKINS_USERNAME: admin

secretName: platform-server-secrets

podAnnotations: {}

podLabels:
  app-role: platform

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readiness:
    path: /readyz
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3

tolerations: []

affinity: {}