image:
  registry: ccr.ccs.tencentyun.com
  repository: k3s-platform/platform-server
  tag: dev
  pullPolicy: Always
  pullSecrets:
    - tcr-platform-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

api:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  nodeSelector:
    platform-role: light
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

worker:
  replicaCount: 1
  nodeSelector:
    platform-role: light
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

config:
  catalogPath: /etc/platform/service-catalog.yaml

env:
  POSTGRES_HOST: platform-postgresql.platform.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: platform_db
  POSTGRES_USER: platform_user

  RABBITMQ_HOST: platform-rabbitmq.platform.svc.cluster.local
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: platform_user

  JENKINS_BASE_URL: http://jenkins.cicd.svc.cluster.local:8080
  JENKINS_USERNAME: admin

secretName: platform-server-secrets

podAnnotations: {}

podLabels:
  app-role: platform

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readiness:
    path: /readyz
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3

tolerations: []

affinity: {}