apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-server.fullname" . }}-api
  labels:
    {{- include "platform-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "platform-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api