apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platform-server.fullname" . }}-config
  labels:
    {{- include "platform-server.labels" . | nindent 4 }}
data:
  service-catalog.yaml: |
{{ .Values.config.serviceCatalog | indent 4 }}