apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "forum-api.fullname" . }}
  labels:
    {{- include "forum-api.labels" . | nindent 4 }}
data:
  APP_PORT: {{ .Values.app.port | quote }}
  MONGO_DATABASE: {{ .Values.app.mongoDatabase | quote }}
